exclude:
  - /publish/.*
  - /packages/annotations-jvm/.*
  - /packages/annotations-kmp/.*

languages:
  - name: kotlin
    production:
      exclude:
        - .*/core-test/.*\.kt
    test:
      include:
        - .*/core-test/.*\.kt

  - name: groovy
    production:
      exclude:
        - .*/core-test/.*\.kt
        - .*Spec\.groovy
    test:
      include:
        - .*/core-test/.*\.kt
        - .*Spec\.groovy

component_depth: 2