github_checks:
  annotations: false

ignore:
  # These classes contain glue code for which code coverage is not recorded
  - lib/klutter-gradle/src/main/kotlin/dev/buijs/klutter/gradle
  # Mostly tested through UI (e2e) tests for which coverage is not recorded
  - lib/klutter-jetbrains/src/main/kotlin/dev/buijs/klutter/jetbrains
  # Integration test tooling
  - lib/klutter-test/src/main/kotlin/dev/buijs/klutter/test