
name: hello
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  klutter:
    path: ../../klutter-dart
#  klutter: ^0.2.4
  squint_json:
    path: ../../squint
  flutter:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.example.hello
        pluginClass: HelloPlugin
      ios:
        pluginClass: HelloPlugin