name: Codecov
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
        working-directory: ./packages/plugin-flutter
      - name: Run tests with coverage
        run: flutter pub run test --coverage="coverage"
        working-directory: ./packages/plugin-flutter
      - name: Convert coverage to ICOV
        run: flutter pub run coverage:format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.packages --report-on=lib
        working-directory: ./packages/plugin-flutter
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: coverage.lcov