name: Publish Dokka to Github Pages

on:
  push:
env:
  KLUTTER_PRIVATE_USERNAME: ${{ secrets.KLUTTER_PRIVATE_USERNAME }}
  KLUTTER_PRIVATE_PASSWORD: ${{ secrets.KLUTTER_PRIVATE_PASSWORD }}
  KLUTTER_PRIVATE_URL: ${{ secrets.KLUTTER_PRIVATE_URL }}

jobs:
  gradle:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          cache: gradle

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Generate the HTML documentation pages
      - name: Generate documentation
        run: gradle dokkaHtmlMultiModule

      # Deploy the HTML documentation to GitHub pages
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build/dokkaSite

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}