name: Publish Dokka to Github Pages

on:
  push:
env:
  KLUTTER_PRIVATE_USERNAME: ${{ secrets.KLUTTER_PRIVATE_USERNAME }}
  KLUTTER_PRIVATE_PASSWORD: ${{ secrets.KLUTTER_PRIVATE_PASSWORD }}
  KLUTTER_PRIVATE_URL: ${{ secrets.KLUTTER_PRIVATE_URL }}
  KLUTTER_JETBRAINS_CERTIFICATE_CHAINS: ${{ secrets.KLUTTER_JETBRAINS_CERTIFICATE_CHAINS }}
  KLUTTER_JETBRAINS_PRIVATE_KEY: ${{ secrets.KLUTTER_JETBRAINS_PRIVATE_KEY }}
  KLUTTER_JETBRAINS_PRIVATE_KEY_PASSWORD: ${{ secrets.KLUTTER_JETBRAINS_PRIVATE_KEY_PASSWORD }}

jobs:
  gradle:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'checkout source'
        uses: actions/checkout@v3
      - name: 'setup java'
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: 'setup gradle'
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 7.4.2
      - name: 'setup flutter'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: 'create docs'
        run: gradle dokkaHtmlMultiModule -p "lib"
      - name: 'upload to github pages'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: lib/build/dokkaSite
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}