name: Publish kommand executable.
on:
  push:
env:
  KLUTTER_PRIVATE_USERNAME: ${{ secrets.KLUTTER_PRIVATE_USERNAME }}
  KLUTTER_PRIVATE_PASSWORD: ${{ secrets.KLUTTER_PRIVATE_PASSWORD }}
  KLUTTER_PRIVATE_URL: ${{ secrets.KLUTTER_PRIVATE_URL }}
  KLUTTER_JETBRAINS_CERTIFICATE_CHAINS: ${{ secrets.KLUTTER_JETBRAINS_CERTIFICATE_CHAINS }}
  KLUTTER_JETBRAINS_PRIVATE_KEY: ${{ secrets.KLUTTER_JETBRAINS_PRIVATE_KEY }}
  KLUTTER_JETBRAINS_PRIVATE_KEY_PASSWORD: ${{ secrets.KLUTTER_JETBRAINS_PRIVATE_KEY_PASSWORD }}
jobs:
  archive-build-artifacts:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - name: 'checkout source'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'install java'
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
          cache: gradle
      - name: 'build distribution'
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 7.4.2
          arguments: clean distZip -p "lib/kommand"
      - name: 'create downloads folder'
        run: mkdir kommander
      - name: 'copy zip to downloads folder'
        run: cp ./lib/kommand/build/distributions/kommand-*.zip kommander
      - name: 'upload downloads folder'
        uses: actions/upload-artifact@v2
        with:
          name: kommander
          path: kommander
