name: Publish Dokka to Github Pages

on:
  push:
    branches:
      - main

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          cache: gradle
      - name: Generate documentation
        working-directory: ./packages
        run: ./gradlew dokkaHtmlMultiModule
      - name: Generate test coverage
        working-directory: ./packages
        run: ./gradlew koverMergedXmlReport -p "packages"
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./packages/build/dokkaSite
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: packages/build/koverage.xml
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}